DROP DATABASE IF EXISTS ESTACIONAMENTO;
CREATE DATABASE ESTACIONAMENTO;

USE ESTACIONAMENTO;
CREATE TABLE CLIENTES(
  CPF INT(11) NOT NULL,
  Nome VARCHAR(40) NOT NULL,
  DataNascimento DATE,
  Email VARCHAR(40),
  DataInclusao DATETIME NOT NULL,

  PRIMARY KEY (CPF)
);

USE ESTACIONAMENTO;
CREATE TABLE MARCA(
  Codigo INT(10) NOT NULL,
  Nome VARCHAR(40) NOT NULL,

  PRIMARY KEY (Codigo)
);

USE ESTACIONAMENTO;
CREATE TABLE VEICULO(
  Placa VARCHAR(12) NOT NULL,
  Modelo VARCHAR(40) NOT NULL,
  Marca INT(10) NOT NULL,

  PRIMARY KEY (Placa),
  FOREIGN KEY (Marca) REFERENCES MARCA (Codigo)
);

USE ESTACIONAMENTO;
CREATE TABLE ESTACIONAMENTOS(
  Codigo INT(10) NOT NULL,
  CPF INT(11) NOT NULL,
  PlacaVeiculo VARCHAR(12) NOT NULL,
  Entrada DATETIME NOT NULL,
  Saida DATETIME,
  ValorHora FLOAT(5,2) NOT NULL,
  Observacao VARCHAR(5000),

  PRIMARY KEY (Codigo),

  FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF),
  FOREIGN KEY (PlacaVeiculo) REFERENCES VEICULO (Placa)
);

USE ESTACIONAMENTO;
CREATE TABLE RECIBOS(
  Codigo INT(10) NOT NULL,
  CPF INT(11) NOT NULL,
  Placa VARCHAR(12) NOT NULL,
  DataPagamento DATE NOT NULL,
  ValorPago FLOAT(10,2) NOT NULL,

  PRIMARY KEY (Codigo),

  FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF),
  FOREIGN KEY (Placa) REFERENCES VEICULO (Placa)
);