SELECT Nome, Email
FROM ESTACIONAMENTO.CLIENTES;

SELECT ESTACIONAMENTOS.Entrada, CLIENTES.Nome, CLIENTES.Email, VEICULO.Placa, VEICULO.Modelo, MARCA.Nome
FROM CLIENTES, ESTACIONAMENTOS, VEICULO, MARCA
WHERE CLIENTES.CPF = ESTACIONAMENTOS.CPF
AND VEICULO.Placa = ESTACIONAMENTOS.PlacaVeiculo
AND MARCA.Codigo = VEICULO.Marca;